#!/usr/bin/env bash
set -ex

here=$(dirname $0)
git_id=$(git rev-parse --short=7 HEAD)

org=vimc
name=youtrack-integration-webhook

if [ "$1" = "--use-vault" ]; then
    . $here/vault_auth.sh
fi

python3 ./save_settings

docker run -d \
    -v $PWD/config.final.json:/app/config.json \
    -p 4567:80 \
    --name youtrack-integration \
    $org/$name:$git_id
